```{r }
txt <- "Was ice-cream better in Soviet Union or in New York? Bla bla. Nice!\n The package https://quanteda.io/reference/index.html. With compounded like New_Jersey"

txt |>
  strsplit("[ |\n|\t|\r]") |>
  unlist() |>
  gsub2("[!?,;]") |>
  stringi::stri_remove_empty()
```
```{r }
#' tokenize words
#'
#' @description
#' A word tokenizer, designed to keep compounded words, like "Covid-19"" or URLs
#'
#' @export
#'
#' @examples
#' txt <- "Was ice-cream better in Soviet Union or in New York? Bla bla, ble. The package https://quanteda.io/reference/index.html is very Nice! There are also compounded words like New_Jersey. The Covid-19 pandemic is very bad. Some,text,like;csv"
#' tokenize_words(txt)
#'
#' txt2 <- c("Was ice-cream better before?", "The Covid-19 brought many problems")
#' tokenize_words(txt2)
tokenize_words <- function(txt, lower = TRUE, unlist = FALSE) {
  txt <- txt |>
    strsplit("[ \n\t\r,;\\|]") |>
    lapply(\(x){
      x |>
        gsub2("[!?,;]") |>
        gsub2("\\W$") |>
        stringi::stri_remove_empty()
    })

  if (lower) {
    txt <- lapply(txt, tolower)
  }

  if (unlist) {
    txt <- unlist(txt)
  }

  return(txt)
}

txt <- "Was ice-cream better in Soviet Union or in New York? Bla bla. The package https://quanteda.io/reference/index.html is very Nice! There are also compounded words like New_Jersey. The Covid-19 pandemic is very bad. Some,text,like;csv|without.spaces"
tokenize_words(txt)
```
