#' Read YAML text as pure text and transform it into a named list
#'
#' @description
#' To build your own complex dict of substitutions, create a text file with the
#' following yml like structure:
#' `key: word1 word2 word3` where word1 word2 word3 will be replaced by key in text.
#' The result of this function can be used with subs_synonyms() to replace
#' patterns in text.
#'
#' @param txt A character vector containing the YAML text to be read.
#' @return A named list where each element corresponds to a key-value pair in the YAML text.
#' @param ... additional parameters of s2v, like sep or keep_wss. see args(s2v)
#'
#' @export
#'
#' @examples
#' "Test: test teste TEST" |> read_yml_dict()
# read_yml_dict <- function(txt, ...) {
read_yml_dict <- function(txt, sep = " ", ...) {
  # getting the s2v default param for separator
  if (is.na(sep) && !exists("sep")) {
    # using the deftaul value from the package
    s2v_sep <- formals(s2v)$sep
  } else {
    s2v_sep <- sep
  }

  # transfoming yml txt into list
  list_ <- txt |>
    strsplit("[\n\t\r]") |>
    unlist() |>
    grep2("^#", invert = T) |>
    stringi::stri_remove_empty() |>
    # lapply(s2v, sep = s2v_sep)
    lapply(s2v, ...)

  list_names <- lapply(list_, function(x) x[1]) |>
    unlist() |>
    gsub2(":.*")
  names(list_) <- list_names
  list_ <- lapply(list_, function(x) x[-1]) #|> unlist() |> gsub2(":.*")
  return(list_)
}


#' Replace different words by a single word
#'
#' @description
#' When dealing with text analysis, a thing may have different strings, or synonyms.
#' This function make it easier to replace in text many synonym words to only one.
#' @param txt The input text where replacements need to be made.
#' @param subst the substitutions. It accepts as input 1) a dataframe, where
#' the column one is the pattern to capture the words do be replaced and the
#' second column is the word that will replace the first; 2) A named list where
#' keys are the target words and values are vectors of synonyms. Normally, this
#' list is generated by function read_yml_dict()
#' @param ic ignore case? default FALSE
#' it works great with function read_yml_dict(), that creates a list from yaml file.
#'
#' @return a list with key that will substitute the elements of list element.
#' @export
#'
#' @examples:
#' dic_subs <- "WEF: World_Economic_Forum W\\.E\\.F\\."
#' subst <- read_yml_dict(dic_subs)
#' txt <- "The World Economic Forum announced that X and Y. The W.E.F. is a lorem ipsum. But the world economic forum lorem ipsum."
#' subs_synonyms(txt, subst)
#' subs_synonyms(txt, subst, ic = TRUE)
subs_synonyms <- function(txt, subst, ic = FALSE) {
  type_of_subst <- class(subst)

  # if (type_of_subst == "vec") {} else if (
  if (any(type_of_subst %in% "data.frame")) {
    stringr::str_replace_all(txt, tibble::deframe(subst))

    # txt |>
    #   dplyr::mutate(
    #     entity = stringr::str_replace_all(entity, tibble::deframe(subst))
  } else {
    pairs_list <- list()

    for (key in names(subst)) {
      # Get the vector elements and create a pair with the key
      pairs_list[[key]] <- data.frame(
        Elements = subst[[key]],
        Name = key
      )
    }

    subs_ <- dplyr::bind_rows(pairs_list)

    if (ic) {
      subs_ <- subs_ |>
        dplyr::mutate(Elements = paste0("(?i)", Elements))
    }

    subs_ <- tibble::deframe(subs_)
    stringr::str_replace_all(txt, subs_)
  }
}
